// <auto-generated />
using System;
using MangoTaika.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangoTaika.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321154927_RemoveConsultantRole")]
    partial class RemoveConsultantRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangoTaika.Data.Entities.Activite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lieu")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.HasIndex("GroupeId");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Actualite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("Actualites");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BrancheId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BrancheId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Branche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomChefUnite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.CodeInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateUtilisation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstUtilise")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UtilisePaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreateurId");

                    b.HasIndex("UtilisePaId");

                    b.ToTable("CodesInvitation");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateObtention")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScoutId");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DemandeAutorisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Budget")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateActivite")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lieu")
                        .HasColumnType("text");

                    b.Property<string>("MotifRejet")
                        .HasColumnType("text");

                    b.Property<string>("MoyensLogistiques")
                        .HasColumnType("text");

                    b.Property<int>("NombreParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("Objectifs")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("TdrContenu")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeActivite")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ValideurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("ValideurId");

                    b.ToTable("DemandesAutorisation");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DemandeGroupe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailResponsable")
                        .HasColumnType("text");

                    b.Property<string>("MotifRejet")
                        .HasColumnType("text");

                    b.Property<string>("Motivation")
                        .HasColumnType("text");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombreMembresPrevus")
                        .HasColumnType("integer");

                    b.Property<string>("Quartier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("TelephoneResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TraiteParId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TraiteParId");

                    b.ToTable("DemandesGroupe");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DocumentActivite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiviteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDocument")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId");

                    b.ToTable("DocumentsActivite");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Galerie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Galeries");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Groupe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomAdjoints")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.HistoriqueFonction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("ScoutId");

                    b.HasIndex("UserId");

                    b.ToTable("HistoriqueFonctions");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.HistoriqueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AncienStatut")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NouveauStatut")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("TicketId");

                    b.ToTable("HistoriquesTicket");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.LivreDor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstValide")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LivreDor");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.MembreHistorique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Periode")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MembresHistoriques");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.MessageTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("TicketId");

                    b.ToTable("MessagesTicket");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.MotCommissaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MotsCommissaire");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relation")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Scout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrancheId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("text");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexe")
                        .HasColumnType("text");

                    b.Property<string>("StatutASCCI")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrancheId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Scouts");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.SuiviDemande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AncienStatut")
                        .HasColumnType("integer");

                    b.Property<string>("Auteur")
                        .HasColumnType("text");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DemandeId")
                        .HasColumnType("uuid");

                    b.Property<int>("NouveauStatut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DemandeId");

                    b.ToTable("SuivisDemande");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneAId")
                        .HasColumnType("uuid");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<string>("CommentaireSatisfaction")
                        .HasColumnType("text");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupeAssigneId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NoteSatisfaction")
                        .HasColumnType("integer");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssigneAId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("GroupeAssigneId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Administrateur",
                            NormalizedName = "ADMINISTRATEUR"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Name = "Gestionnaire",
                            NormalizedName = "GESTIONNAIRE"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Name = "Scout",
                            NormalizedName = "SCOUT"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            Name = "Superviseur",
                            NormalizedName = "SUPERVISEUR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ParentScout", b =>
                {
                    b.Property<Guid>("ParentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScoutsId")
                        .HasColumnType("uuid");

                    b.HasKey("ParentsId", "ScoutsId");

                    b.HasIndex("ScoutsId");

                    b.ToTable("ParentScout");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Activite", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId");

                    b.Navigation("Createur");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Actualite", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.ApplicationUser", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Branche", "Branche")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("BrancheId");

                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany("Membres")
                        .HasForeignKey("GroupeId");

                    b.Navigation("Branche");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Branche", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany("Branches")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.CodeInvitation", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "UtilisePar")
                        .WithMany()
                        .HasForeignKey("UtilisePaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Createur");

                    b.Navigation("UtilisePar");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Competence", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Scout", "Scout")
                        .WithMany("Competences")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DemandeAutorisation", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId");

                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Demandeur");

                    b.Navigation("Groupe");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DemandeGroupe", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "TraitePar")
                        .WithMany()
                        .HasForeignKey("TraiteParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TraitePar");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DocumentActivite", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Activite", "Activite")
                        .WithMany("Documents")
                        .HasForeignKey("ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activite");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Groupe", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.HistoriqueFonction", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId");

                    b.HasOne("MangoTaika.Data.Entities.Scout", "Scout")
                        .WithMany("HistoriqueFonctions")
                        .HasForeignKey("ScoutId");

                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "User")
                        .WithMany("HistoriqueFonctions")
                        .HasForeignKey("UserId");

                    b.Navigation("Groupe");

                    b.Navigation("Scout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.HistoriqueTicket", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangoTaika.Data.Entities.Ticket", "Ticket")
                        .WithMany("Historiques")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.MessageTicket", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Scout", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Branche", "Branche")
                        .WithMany("Scouts")
                        .HasForeignKey("BrancheId");

                    b.HasOne("MangoTaika.Data.Entities.Groupe", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeId");

                    b.Navigation("Branche");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.SuiviDemande", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.DemandeAutorisation", "Demande")
                        .WithMany("Suivis")
                        .HasForeignKey("DemandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Ticket", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "AssigneA")
                        .WithMany()
                        .HasForeignKey("AssigneAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", "Createur")
                        .WithMany("Tickets")
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.Groupe", "GroupeAssigne")
                        .WithMany()
                        .HasForeignKey("GroupeAssigneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssigneA");

                    b.Navigation("Createur");

                    b.Navigation("GroupeAssigne");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParentScout", b =>
                {
                    b.HasOne("MangoTaika.Data.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaika.Data.Entities.Scout", null)
                        .WithMany()
                        .HasForeignKey("ScoutsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Activite", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("HistoriqueFonctions");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Branche", b =>
                {
                    b.Navigation("Scouts");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.DemandeAutorisation", b =>
                {
                    b.Navigation("Suivis");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Groupe", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Membres");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Scout", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("HistoriqueFonctions");
                });

            modelBuilder.Entity("MangoTaika.Data.Entities.Ticket", b =>
                {
                    b.Navigation("Historiques");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
